import React from "react";
import Footer from "./Components/Footer/Footer";
import NavBar from "./Components/NavBar/NavBar";
import TopHeader from "./Components/TopHeader/TopHeader";
import styled from "styled-components";

const Banner = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  background-color: white;
  height: 55vh;
  @media (max-width: 465px) {
    height: 40vh;
  }
`;
const BannerText = styled.h1`
  margin-top: 100px;
  color: #00af32;
  font-weight: bolder;
  font-size: 60px;
  @media (max-width: 465px) {
    font-size: 30px;
  }
`;

const Content = styled.div`
  padding: 20px;

  margin-bottom: 50px;
  @media (max-width: 465px) {
    margin-bottom: 25px;
  }
`;

const Header = styled.h1`
  text-align: center;
  font-size: 30px;
  color: gray;
  font-weight: bold;
  margin: 20px;
  @media (max-width: 465px) {
    font-size: 25px;
  }
`;

const SubHeader = styled.h2`
  text-align: center;
  color: #00af32;
  font-size: 20px;
  margin: 20px;
  @media (max-width: 465px) {
    margin: 10px;
    font-size: 18px;
  }
`;
const SubHeaderTilte = styled.h3`
  font-size: 18px;
  text-align: left;
  margin: 10px 20px;
  @media (max-width: 465px) {
    margin: 5px 0px;
    font-size: 12px;
  }
`;
const SubHeaderSubTitle = styled.p`
  color: black;
  font-weight: bold;
  margin: 10px 20px;
  @media (max-width: 465px) {
    margin: 5px 0px;
    font-size: 12px;
  }
`;

const Text = styled.p`
  font-size: 16px;
  text-align: left;
  margin: 10px 20px;
  @media (max-width: 465px) {
    margin: 5px 0px;
    font-size: 12px;
  }
`;
const Email = styled.a`
  text-align: left;
  text-decoration: none;
  color: black;
  @media (max-width: 465px) {
    font-size: 12px;
  }
`;

const PrivacyPolicy = () => {
  return (
    <div>
      <TopHeader />
      <NavBar />
      <Banner>
        <BannerText>#OurPrivacyPolicy</BannerText>
      </Banner>
      <Content>
        <Header>Privacy Policy</Header>
        <Text>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
          <br />
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the Privacy Policy Template.
        </Text>
        <SubHeader>Interpretation and Definitions</SubHeader>
        <SubHeaderTilte>Interpretation</SubHeaderTilte>
        <Text>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Text>
        <SubHeaderTilte> Definitions</SubHeaderTilte>
        <Text>
          For the purposes of this Privacy Policy: Account means a unique
          account created for You to access our Service or parts of our Service.
          <br />
          Affiliate means an entity that controls, is controlled by or is under
          common control with a party, where "control" means ownership of 50% or
          more of the shares, equity interest or other securities entitled to
          vote for election of directors or other managing authority.
          <br />
          Application means the software program provided by the Company
          downloaded by You on any electronic device, named Tranzakt Company
          (referred to as either "the Company", "We", "Us" or "Our" in this
          Agreement) refers to Scuudu Labs limited, Lifestyle and Golf City, KM
          7 Port Harcourt - Enugu Expy, Ugwuaji 400108, Enugu. Country refers
          to: Nigeria Device means any device that can access the Service such
          as a computer, a cellphone or a digital tablet.
          <br /> Personal Data is any information that relates to an identified
          or identifiable individual. Service refers to the Application. Service
          Provider means any natural or legal person who processes the data on
          behalf of the Company.
          <br />
          It refers to third-party companies or individuals employed by the
          Company to facilitate the Service, to provide the Service on behalf of
          the Company, to perform services related to the Service or to assist
          the Company in analyzing how the Service is used. <br />
          Usage Data refers to data collected automatically, either generated by
          the use of the Service or from the Service infrastructure itself (for
          example, the duration of a page visit).
          <br />
          You means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable. Collecting and Using
          Your Personal Data
        </Text>
        <SubHeader>Types of Data Collected</SubHeader>
        <SubHeaderTilte>Personal Data</SubHeaderTilte>
        <Text>
          Personal Data
          <br />
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You.
          <br /> Personally identifiable information may include, but is not
          limited to:
          <br />
          Email address
          <br />
          First name and last name
          <br />
          Phone number
          <br />
          Address, State, Province, ZIP/Postal code, City
          <br />
        </Text>
        <SubHeaderTilte>Usage Data</SubHeaderTilte>
        <Text>
          Usage Data is collected automatically when using the Service.
          <br />
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
          <br />
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
          <br />
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
          <br />
        </Text>
        <SubHeaderTilte>
          Information Collected while Using the Application
        </SubHeaderTilte>
        <Text>
          While using Our Application, in order to provide features of Our
          Application, We may collect, with Your prior permission:
          <br />
          Information from your Device's phone book (contacts list) We use this
          information to provide features of Our Service, to improve and
          customize Our Service. The information may be uploaded to the
          Company's servers and/or a Service Provider's server or it may be
          simply stored on Your device.
          <br />
          You can enable or disable access to this information at any time,
          through Your Device settings.
        </Text>
        <SubHeaderTilte>Use of Your Personal Data</SubHeaderTilte>
        <Text>
          The Company may use Personal Data for the following purposes:
          <br />
          To provide and maintain our Service, including to monitor the usage of
          our Service.
          <br />
          To manage Your Account: to manage Your registration as a user of the
          Service. The Personal Data You provide can give You access to
          different functionalities of the Service that are available to You as
          a registered user.
          <br />
        </Text>
        <SubHeaderSubTitle>
          For the performance of a contract:
        </SubHeaderSubTitle>{" "}
        <Text>
          the development, compliance and undertaking of the purchase contract
          for the products, items or services You have purchased or of any other
          contract with Us through the Service.
          <br />
        </Text>
        <SubHeaderSubTitle>To contact You:</SubHeaderSubTitle>
        <Text>
          {" "}
          To contact You by email, telephone calls, SMS, or other equivalent
          forms of electronic communication, such as a mobile application's push
          notifications regarding updates or informative communications related
          to the functionalities, products or contracted services, including the
          security updates, when necessary or reasonable for their
          implementation.
          <br />
          To provide You with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless You
          have opted not to receive such information.
          <br />
        </Text>
        <SubHeaderSubTitle>To manage Your requests:</SubHeaderSubTitle>{" "}
        <Text>
          To attend and manage Your requests to Us.
          <br />
          For business transfers: We may use Your information to evaluate or
          conduct a merger, divestiture, restructuring, reorganization,
          dissolution, or other sale or transfer of some or all of Our assets,
          whether as a going concern or as part of bankruptcy, liquidation, or
          similar proceeding, in which Personal Data held by Us about our
          Service users is among the assets transferred.
          <br />
        </Text>
        <SubHeaderSubTitle>For other purposes:</SubHeaderSubTitle>
        <Text>
          {" "}
          We may use Your information for other purposes, such as data analysis,
          identifying usage trends, determining the effectiveness of our
          promotional campaigns and to evaluate and improve our Service,
          products, services, marketing and your experience.
          <br />
        </Text>
        <SubHeader>
          We may share Your personal information in the following situations:
        </SubHeader>
        <SubHeaderSubTitle>With Service Providers:</SubHeaderSubTitle>
        <Text>
          {" "}
          We may share Your personal information with Service Providers to
          monitor and analyze the use of our Service, to contact You.
          <br />
        </Text>
        <SubHeaderSubTitle>For business transfers:</SubHeaderSubTitle>{" "}
        <Text>
          {" "}
          We may share or transfer Your personal information in connection with,
          or during negotiations of, any merger, sale of Company assets,
          financing, or acquisition of all or a portion of Our business to
          another company.
          <br />
          With Affiliates: We may share Your information with Our affiliates, in
          which case we will require those affiliates to honor this Privacy
          Policy. Affiliates include Our parent company and any other
          subsidiaries, joint venture partners or other companies that We
          control or that are under common control with Us.
          <br />
        </Text>
        <SubHeaderSubTitle>With business partners:</SubHeaderSubTitle>
        <Text>
          We may share Your information with Our business partners to offer You
          certain products, services or promotions. With other users: when You
          share personal information or otherwise interact in the public areas
          with other users, such information may be viewed by all users and may
          be publicly distributed outside.
          <br />
        </Text>
        <SubHeaderSubTitle>With Your consent:</SubHeaderSubTitle>
        <Text>
          {" "}
          We may disclose Your personal information for any other purpose with
          Your consent. Retention of Your Personal Data
          <br />
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
          <br />
        </Text>
        <Text>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </Text>
        <SubHeaderTilte>Transfer of Your Personal Data</SubHeaderTilte>
        <Text>
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the parties
          involved in the processing are located. It means that this information
          may be transferred to — and maintained on — computers located outside
          of Your state, province, country or other governmental jurisdiction
          where the data protection laws may differ than those from Your
          jurisdiction.
        </Text>
        <Text>
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </Text>
        <Text>
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </Text>
        <SubHeader>Disclosure of Your Personal Data</SubHeader>
        <SubHeaderTilte>Business Transactions</SubHeaderTilte>
        <Text>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </Text>
        <SubHeaderTilte>Law enforcement</SubHeaderTilte>
        <Text>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </Text>
        <SubHeaderTilte>Other legal requirements</SubHeaderTilte>
        <Text>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </Text>
        <Text>
          Comply with a legal obligation
          <br />
          Protect and defend the rights or property of the Company
          <br />
          Prevent or investigate possible wrongdoing in connection with the
          Service
          <br />
          Protect the personal safety of Users of the Service or the public
          <br />
          Protect against legal liability
          <br />
          Security of Your Personal Data
          <br />
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </Text>
        <SubHeader>Children's Privacy</SubHeader>
        <Text>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Persona
        </Text>
        <Text>
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent's consent before We collect and use that
          information.
        </Text>
        <SubHeader>Links To Other Websites</SubHeader>
        <Text>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit.
        </Text>
        <Text>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </Text>
        <SubHeader>Changes to this Privacy Policy</SubHeader>
        <Text>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
          <br />
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the "Last
          updated" date at the top of this Privacy Policy.
          <br />
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </Text>
        <SubHeaderTilte>Contact Us :</SubHeaderTilte>
        <Text>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </Text>
        <Text>
          <Email href="mailt:hello@scuudu.com"> By email:info@scuudu.com</Email>
        </Text>
      </Content>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
